export class Type {
  constructor() {
    this.mediaData = this.#getMedia();
  }

  getMediaForType(type) {
    return this.mediaData.filter((res) => res.type === type);
  }

  getMediaNameForType(type) {
    return this.getMediaForType(type).map((item) => item.name);
  }

  // 私有方法，不对外直接提供
  #getMedia() {
    return [
      { name: "中央电视台", type: "电视" },
      { name: "中国国际电视台", type: "电视" },
      { name: "中国教育网络电视台", type: "电视" },
      { name: "北京卫视", type: "电视" },
      { name: "天津卫视", type: "电视" },
      { name: "河北卫视", type: "电视" },
      { name: "山西卫视", type: "电视" },
      { name: "内蒙古卫视", type: "电视" },
      { name: "辽宁卫视", type: "电视" },
      { name: "吉林卫视", type: "电视" },
      { name: "黑龙江卫视", type: "电视" },
      { name: "东方卫视", type: "电视" },
      { name: "江苏卫视", type: "电视" },
      { name: "浙江卫视", type: "电视" },
      { name: "安徽卫视", type: "电视" },
      { name: "东南卫视", type: "电视" },
      { name: "江西卫视", type: "电视" },
      { name: "山东卫视", type: "电视" },
      { name: "河南卫视", type: "电视" },
      { name: "湖北卫视", type: "电视" },
      { name: "湖南卫视", type: "电视" },
      { name: "广东卫视", type: "电视" },
      { name: "广西卫视", type: "电视" },
      { name: "海南卫视", type: "电视" },
      { name: "重庆卫视", type: "电视" },
      { name: "四川卫视", type: "电视" },
      { name: "贵州卫视", type: "电视" },
      { name: "云南卫视", type: "电视" },
      { name: "西藏卫视", type: "电视" },
      { name: "陕西卫视", type: "电视" },
      { name: "甘肃卫视", type: "电视" },
      { name: "青海卫视", type: "电视" },
      { name: "宁夏卫视", type: "电视" },
      { name: "新疆卫视", type: "电视" },
      { name: "兵团卫视", type: "电视" },
      { name: "中央人民广播电台", type: "电台" },
      { name: "中国国际广播电台", type: "电台" },
      { name: "北京人民广播电台", type: "电台" },
      { name: "上海人民广播电台", type: "电台" },
      { name: "重庆人民广播电台", type: "电台" },
      { name: "河北人民广播电台", type: "电台" },
      { name: "山西人民广播电台", type: "电台" },
      { name: "内蒙古人民广播电台", type: "电台" },
      { name: "辽宁人民广播电台", type: "电台" },
      { name: "吉林人民广播电台", type: "电台" },
      { name: "黑龙江人民广播电台", type: "电台" },
      { name: "江苏人民广播电台", type: "电台" },
      { name: "浙江人民广播电台", type: "电台" },
      { name: "安徽人民广播电台", type: "电台" },
      { name: "江西人民广播电台", type: "电台" },
      { name: "山东人民广播电台", type: "电台" },
      { name: "河南人民广播电台", type: "电台" },
      { name: "湖北人民广播电台", type: "电台" },
      { name: "广东人民广播电台", type: "电台" },
      { name: "海南人民广播电台", type: "电台" },
      { name: "广西人民广播电台", type: "电台" },
      { name: "贵州人民广播电台", type: "电台" },
      { name: "陕西人民广播电台", type: "电台" },
      { name: "甘肃人民广播电台", type: "电台" },
      { name: "湖南人民广播电台", type: "电台" },
      { name: "宁夏人民广播电台", type: "电台" },
      { name: "青海人民广播电台", type: "电台" },
      { name: "四川人民广播电台", type: "电台" },
      { name: "天津人民广播电台", type: "电台" },
      { name: "云南人民广播电台", type: "电台" },
      { name: "福建人民广播电台", type: "电台" },
      { name: "新疆人民广播电台", type: "电台" },
      { name: "西藏人民广播电台", type: "电台" },
      { name: "新疆生产建设兵团人民广播电台", type: "电台" },
      { name: "人民日报", type: "纸媒" },
      { name: "人民日报海外版", type: "纸媒" },
      { name: "解放军报", type: "纸媒" },
      { name: "光明日报", type: "纸媒" },
      { name: "经济日报", type: "纸媒" },
      { name: "经济参考报", type: "纸媒" },
      { name: "法制日报", type: "纸媒" },
      { name: "科技日报", type: "纸媒" },
      { name: "工人日报", type: "纸媒" },
      { name: "中国日报英文版", type: "纸媒" },
      { name: "中国青年报", type: "纸媒" },
      { name: "中国交通报", type: "纸媒" },
      { name: "环球时报", type: "纸媒" },
      { name: "新华每日电讯", type: "纸媒" },
      { name: "中国妇女报", type: "纸媒" },
      { name: "中国纪检监察报", type: "纸媒" },
      { name: "人民铁道报", type: "纸媒" },
      { name: "人民画报", type: "纸媒" },
      { name: "中国教育报", type: "纸媒" },
      { name: "中国财经报", type: "纸媒" },
      { name: "检察日报", type: "纸媒" },
      { name: "人民法院报", type: "纸媒" },
      { name: "中国文化报", type: "纸媒" },
      { name: "中国水利报", type: "纸媒" },
      { name: "国际商报", type: "纸媒" },
      { name: "中国劳动保障报", type: "纸媒" },
      { name: "中国工商报", type: "纸媒" },
      { name: "人民邮电报", type: "纸媒" },
      { name: "中国建设报", type: "纸媒" },
      { name: "中国环境报", type: "纸媒" },
      { name: "人民公安报", type: "纸媒" },
      { name: "中国审计报", type: "纸媒" },
      { name: "中国应急管理报", type: "纸媒" },
      { name: "中国质量报", type: "纸媒" },
      { name: "北京日报", type: "纸媒" },
      { name: "河北日报", type: "纸媒" },
      { name: "山西日报", type: "纸媒" },
      { name: "内蒙古日报", type: "纸媒" },
      { name: "天津日报", type: "纸媒" },
      { name: "新华日报", type: "纸媒" },
      { name: "辽宁日报", type: "纸媒" },
      { name: "吉林日报", type: "纸媒" },
      { name: "黑龙江日报", type: "纸媒" },
      { name: "浙江日报", type: "纸媒" },
      { name: "安徽日报", type: "纸媒" },
      { name: "福建日报", type: "纸媒" },
      { name: "湖北日报", type: "纸媒" },
      { name: "湖南日报", type: "纸媒" },
      { name: "广西日报", type: "纸媒" },
      { name: "大众日报", type: "纸媒" },
      { name: "南方日报", type: "纸媒" },
      { name: "海南日报", type: "纸媒" },
      { name: "四川日报", type: "纸媒" },
      { name: "贵州日报", type: "纸媒" },
      { name: "云南日报", type: "纸媒" },
      { name: "西藏日报", type: "纸媒" },
      { name: "陕西日报", type: "纸媒" },
      { name: "甘肃日报", type: "纸媒" },
      { name: "青海日报", type: "纸媒" },
      { name: "宁夏日报", type: "纸媒" },
      { name: "解放日报", type: "纸媒" },
      { name: "新疆日报", type: "纸媒" },
      { name: "河南日报", type: "纸媒" },
      { name: "江西日报", type: "纸媒" },
      { name: "重庆日报", type: "纸媒" },
      { name: "兵团日报", type: "纸媒" },
      { name: "澳门日报", type: "纸媒" },
      { name: "华侨报", type: "纸媒" },
      { name: "大公报", type: "纸媒" },
      { name: "新华社", type: "通讯社" },
      { name: "中新社", type: "通讯社" },
      { name: "学习强国平台", type: "APP" },
    ];
  }
}
